[package]
name = "mason-registry-api"
version = "1.0.0"
authors = [ "William Boman <william@redwill.se>" ]
edition = "2018"

[dependencies]
http = "0.1"
serde_json = "1.0"
url = "2.3.1"
vercel_lambda = "*"

  [dependencies.reqwest]
  version = "0.11"
  features = [ "blocking", "json" ]

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]

[[bin]]
name = "latest-version"
path = "/Users/williamboman/Developer/github/mason-registry-api/api/npm/[scope]/[package]/latest-version.rs"
