[package]
name = "github-api-proxy"
version = "1.0.0"
authors = ["William Boman <william@redwill.se>"]
edition = "2018"

[dependencies]
http = "0.1"
vercel_lambda = "*"
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
features = ["blocking", "json"]

[[bin]]
name = "latest-tag"
path = "repo/[owner]/[name]/latest-tag.rs"

[[bin]]
name = "latest-release"
path = "repo/[owner]/[name]/latest-release.rs"
