[package]
name = "index"
version = "1.0.0"
authors = [ "William Boman <william@redwill.se>" ]
edition = "2018"

[dependencies]
http = "0.1"
vercel_lambda = "*"
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.reqwest]
version = "0.11"
features = [ "blocking", "json" ]

[[bin]]
name = "latest-tag"
path = "/Users/williamboman/Developer/github/github-api-latest-tag-proxy/api/repo/[owner]/[name]/latest-tag.rs"
