---
name: Cargo upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1

jobs:
  cargo-upgrade:
    name: Cargo upgrade
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: Run cargo upgrade
        run: cargo upgrade
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
            token: ${{ secrets.PAT }}
            author: "William Botman <william+bot@redwill.se>"
            committer: "William Botman <william+bot@redwill.se>"
            add-paths: |
              Cargo.toml
              Cargo.lock
            commit-message: "chore(deps): upgrade deps"
            title: "chore(deps): upgrade deps"
            branch: chore/upgrade-deps
