---
name: Schema tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  schema-test:
    name: Run schema tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25.1.0
        if: ${{ github.event_name == 'pull_request' }}
        id: deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      - name: Run schema tests
        run: |
          npm install -g ajv ajv-cli ajv-formats
          ./tests/validate-schema.sh
        env:
          GITHUB_API_KEY: ${{ secrets.API_KEY_GITHUB }}
          BASE_URL: ${{ steps.deploy.outputs.preview-url }}
