---
name: Schema tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  schema-test:
    name: Run schema tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run schema tests
        run: |
          echo "::add-mask::${{ secrets.VERCEL_TOKEN }}"
          npm install -g ajv ajv-cli ajv-formats vercel
          vercel dev --listen 3000 --token "${{ secrets.VERCEL_TOKEN }}" --yes &
          while ! nc -zvw1 localhost 3000; do sleep 1; done
          BASE_URL=http://localhost:3000 ./tests/validate-schema.sh
          kill -9 `jobs -p`
        env:
          GITHUB_API_KEY: ${{ secrets.API_KEY_GITHUB }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
